#!/bin/bash
# راه‌اندازی سریع Auto-Dev-LLM با API سفارشی

set -e  # توقف در صورت خطا

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║         🚀 Auto-Dev-LLM Quick Setup 🚀                       ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# رنگ‌ها
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# تابع کمکی
print_step() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# گام 1: بررسی Python
echo "📋 گام 1: بررسی Python..."
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version)
    print_step "Python یافت شد: $PYTHON_VERSION"
else
    print_error "Python 3 یافت نشد! لطفاً نصب کنید."
    exit 1
fi

# گام 2: ایجاد محیط مجازی
echo ""
echo "📋 گام 2: محیط مجازی..."
if [ ! -d "venv" ]; then
    print_step "ایجاد محیط مجازی..."
    python3 -m venv venv
else
    print_warning "محیط مجازی از قبل وجود دارد"
fi

# فعال‌سازی
source venv/bin/activate
print_step "محیط مجازی فعال شد"

# گام 3: نصب وابستگی‌ها
echo ""
echo "📋 گام 3: نصب کتابخانه‌ها..."
pip install -q --upgrade pip
pip install -q -r requirements.txt
print_step "کتابخانه‌ها نصب شدند"

# گام 4: ایجاد ساختار پوشه‌ها
echo ""
echo "📋 گام 4: ایجاد پوشه‌ها..."
mkdir -p specs logs backups src/core src/llm src/managers src/utils tests
print_step "ساختار پوشه‌ها آماده شد"

# گام 5: تنظیم API Key
echo ""
echo "📋 گام 5: تنظیم API Key..."

if [ -f ".env" ]; then
    print_warning ".env از قبل وجود دارد"
    read -p "آیا می‌خواهید دوباره تنظیم کنید؟ (y/n): " RECONFIGURE
    if [ "$RECONFIGURE" != "y" ]; then
        RECONFIGURE="n"
    fi
else
    RECONFIGURE="y"
fi

if [ "$RECONFIGURE" = "y" ]; then
    echo ""
    echo "لطفاً اطلاعات API خود را وارد کنید:"
    echo ""
    
    # انتخاب provider
    echo "انتخاب کنید:"
    echo "1) OpenRouter (پیشنهادی)"
    echo "2) Anthropic مستقیم"
    echo "3) Groq (رایگان)"
    echo "4) سرور سفارشی"
    read -p "انتخاب (1-4): " PROVIDER_CHOICE
    
    case $PROVIDER_CHOICE in
        1)
            read -p "OpenRouter API Key: " API_KEY
            API_URL="https://openrouter.ai/api/v1"
            MODEL="anthropic/claude-sonnet-4-20250514"
            ;;
        2)
            read -p "Anthropic API Key: " API_KEY
            API_URL="https://api.anthropic.com/v1"
            MODEL="claude-sonnet-4-20250514"
            ;;
        3)
            read -p "Groq API Key: " API_KEY
            API_URL="https://api.groq.com/openai/v1"
            MODEL="llama-3.1-70b-versatile"
            ;;
        4)
            read -p "آدرس سرور (مثلاً https://api.example.com/v1): " API_URL
            read -p "API Key: " API_KEY
            read -p "نام مدل: " MODEL
            ;;
        *)
            print_error "انتخاب نامعتبر"
            exit 1
            ;;
    esac
    
    # ذخیره در .env
    cat > .env << EOF
# API Configuration
CUSTOM_API_KEY=$API_KEY
CUSTOM_API_URL=$API_URL
CUSTOM_API_MODEL=$MODEL

# Generated by setup script
# $(date)
EOF
    
    print_step ".env ایجاد شد"
    
    # بروزرسانی spec file
    cat > specs/self_development_spec.yaml << EOF
project_name: "auto-dev-llm-self-improvement"
description: "توسعه خود سیستم"
version: "0.2.0"

llm:
  mode: "online"
  custom_api:
    enabled: true
    base_url: "$API_URL"
    api_key_env: "CUSTOM_API_KEY"
    model: "$MODEL"
    timeout: 300
    retry: 3
  online:
    use_cache: true
    max_tokens: 3000
    temperature: 0.7
  fallback_online: false
  fallback_to_mcp: false

scheduler:
  active_hours:
    start: 0
    end: 24
  max_concurrent_tasks: 2
  check_interval: 30
  cpu_threshold: 85

cost_control:
  enabled: true
  max_cost_per_task: 0.10
  max_total_cost: 1.00
  warn_threshold: 0.50
  max_input_tokens: 2000
  max_output_tokens: 3000

git:
  auto_commit: true
  commit_message_template: "🤖 Auto: {task_name}"
  branch_pattern: "auto-dev/{feature_name}"
  auto_push: false

logging:
  log_path: "./logs"
  level: "INFO"
  per_feature_log: true

rollback:
  enabled: true
  backup_path: "./backups"
  max_backups: 20

features:
  - name: "git-automation"
    priority: 1
    description: "Git automation"
    tasks:
      - name: "git-wrapper"
        description: "Git operations wrapper"
        files: ["src/utils/git_utils.py"]
        tests: ["tests/test_git_utils.py"]
EOF
    
    print_step "spec file بروزرسانی شد"
fi

# گام 6: تست اتصال
echo ""
echo "📋 گام 6: تست اتصال..."
python3 dry_run_test.py
if [ $? -eq 0 ]; then
    print_step "تست موفق بود!"
else
    print_warning "تست ناموفق - لطفاً تنظیمات را بررسی کنید"
fi

# گام 7: محاسبه هزینه
echo ""
echo "📋 گام 7: برآورد هزینه..."
python3 << EOF
# محاسبه هزینه
input_tokens = 27000
output_tokens = 45000

# قیمت Sonnet 4.5
input_cost = (input_tokens * 3.00) / 1_000_000
output_cost = (output_tokens * 15.00) / 1_000_000
total = input_cost + output_cost

print(f"\n{'='*50}")
print(f"💰 برآورد هزینه کل پروژه:")
print(f"{'='*50}")
print(f"Input:  {input_tokens:,} tokens × \$3.00/1M  = \${input_cost:.3f}")
print(f"Output: {output_tokens:,} tokens × \$15.00/1M = \${output_cost:.3f}")
print(f"{'-'*50}")
print(f"کل: \${total:.2f}")
print(f"{'='*50}\n")
EOF

# نمایش آمار
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                   ✅ راه‌اندازی کامل شد!                    ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 آمار پروژه:"
echo "   • Features: 8"
echo "   • Tasks: 18"
echo "   • Files: ~36"
echo "   • Estimated time: 20-30 minutes"
echo "   • Estimated cost: ~\$0.76"
echo ""
echo "🚀 دستورات بعدی:"
echo ""
echo "   1️⃣  تست سریع (رایگان):"
echo "       python3 dry_run_test.py"
echo ""
echo "   2️⃣  اجرای کامل:"
echo "       python3 bootstrap_self_dev.py"
echo ""
echo "   3️⃣  اجرای یک feature:"
echo "       python3 main.py --batch --features git-automation"
echo ""
echo "📖 مستندات:"
echo "   • COST_ESTIMATION.md"
echo "   • CUSTOM_API_SETUP.md"
echo "   • SELF_DEVELOPMENT.md"
echo ""
echo "💡 نکته: برای فعال‌سازی محیط مجازی:"
echo "   source venv/bin/activate"
echo ""
echo "آماده هستید! 🎉"